restart-times: 2
max-jobs-per-second: 1
max-status-checks-per-second: 10
jobs: 10
keep-going: true
reason: true
printshellcmds: true
conda-prefix: .snakemake/conda
singularity-prefix: .snakemake/singularity
rerun-triggers: mtime
use-conda: true
use-singularity: true
