samples: config/samples.tsv
tumor_normal_pairs: config/tumor_normal_pairs.tsv

gcloud:
  gs_bam_bucket: "gs://tcga_wxs_bam"
  gs_res_bucket: "gs://facets_tcga_results"


target_files:
  bed:
    whole_exome_agilent_1.1_refsef_plus_3_boosters: resources/target_files/whole_exome_agilent_1.1_refseq_plus_3_boosters.targetIntervals.liftover_hg38.bed
  bed_padded:
    whole_exome_agilent_1.1_refsef_plus_3_boosters: resources/target_files/whole_exome_agilent_1.1_refseq_plus_3_boosters.targetIntervals.liftover_hg38.padded_10n.bed

params:
    civic:
        code_dir: external/CivicAnnotator
        data_dir: external/CivicAnnotator/data
        gene_list: external/CivicAnnotator/data/01-Jan-2022-GeneSummaries.tsv
        evidences: external/CivicAnnotator/data/01-Jan-2022-ClinicalEvidenceSummaries_Annotated.xlsx
        run_per_sample:
          cna: true
        rules_clean: external/CivicAnnotator/data/CIViC_Curation_And_Rules_Mutation.xlsx
    cnv:
        bed: resources/gene_set/Homo_sapiens.GRCh38.104.gff3.gene.bed
        calls_threshold: 10
        facets:
            cvals:
                pre: 25
                pro: 500
                purity: 1000
            gbuild: hg38
        chr_arm_rules: resources/facets_suite/facets_suite_arm_level_rules.xlsx
        cna_cat_rules: resources/facets_suite/facets_scna_categories_rules.xlsx
    gatk:
        known_sites: resources/hg38_gatk/af-only-gnomad.hg38.vcf.gz
    oncokb:
        code_dir: external/oncokb-annotator
        data_dir: external/oncokb-annotator/data
        gene_list: resources/oncokb/cancerGeneList_10_01_2022.tsv
        run_per_sample:
          cna: true
        token: 722c8d78-b8c0-408c-9ecb-4bd51354e93a
        rules_clean: resources/oncokb/OncoKB_Curation_And_Rules.xlsx

# start_from should be one of
# - 1: download_bam
# - 2: get_snp_pileup
# - 3: somatic_cnv_facets
# - 4: somatic_cnv_process_vcf
start_from: download_bam
